# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /root/.cache/JetBrains/RemoteDev/dist/9e0128be961c6_CLion-2025.1/bin/cmake/linux/x64/bin/cmake

# The command to remove a file.
RM = /root/.cache/JetBrains/RemoteDev/dist/9e0128be961c6_CLion-2025.1/bin/cmake/linux/x64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/CLionProjects/bastion-auth

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/CLionProjects/bastion-auth

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/root/.cache/JetBrains/RemoteDev/dist/9e0128be961c6_CLion-2025.1/bin/cmake/linux/x64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/CLionProjects/bastion-auth/CMakeFiles /root/CLionProjects/bastion-auth//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/CLionProjects/bastion-auth/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/CLionProjects/bastion-auth/CMakeFiles /root/CLionProjects/bastion-auth//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /root/CLionProjects/bastion-auth/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bastion_data

# Build rule for target.
bastion_data: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bastion_data
.PHONY : bastion_data

# fast build rule for target.
bastion_data/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/build
.PHONY : bastion_data/fast

#=============================================================================
# Target rules for targets named bastion_auth

# Build rule for target.
bastion_auth: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bastion_auth
.PHONY : bastion_auth

# fast build rule for target.
bastion_auth/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/build
.PHONY : bastion_auth/fast

APNS/ios_notifications.o: APNS/ios_notifications.cpp.o
.PHONY : APNS/ios_notifications.o

# target to build an object file
APNS/ios_notifications.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/APNS/ios_notifications.cpp.o
.PHONY : APNS/ios_notifications.cpp.o

APNS/ios_notifications.i: APNS/ios_notifications.cpp.i
.PHONY : APNS/ios_notifications.i

# target to preprocess a source file
APNS/ios_notifications.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/APNS/ios_notifications.cpp.i
.PHONY : APNS/ios_notifications.cpp.i

APNS/ios_notifications.s: APNS/ios_notifications.cpp.s
.PHONY : APNS/ios_notifications.s

# target to generate assembly for a file
APNS/ios_notifications.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/APNS/ios_notifications.cpp.s
.PHONY : APNS/ios_notifications.cpp.s

AWS_SES_LAMBDA/AWS_manager.o: AWS_SES_LAMBDA/AWS_manager.cpp.o
.PHONY : AWS_SES_LAMBDA/AWS_manager.o

# target to build an object file
AWS_SES_LAMBDA/AWS_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/AWS_SES_LAMBDA/AWS_manager.cpp.o
.PHONY : AWS_SES_LAMBDA/AWS_manager.cpp.o

AWS_SES_LAMBDA/AWS_manager.i: AWS_SES_LAMBDA/AWS_manager.cpp.i
.PHONY : AWS_SES_LAMBDA/AWS_manager.i

# target to preprocess a source file
AWS_SES_LAMBDA/AWS_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/AWS_SES_LAMBDA/AWS_manager.cpp.i
.PHONY : AWS_SES_LAMBDA/AWS_manager.cpp.i

AWS_SES_LAMBDA/AWS_manager.s: AWS_SES_LAMBDA/AWS_manager.cpp.s
.PHONY : AWS_SES_LAMBDA/AWS_manager.s

# target to generate assembly for a file
AWS_SES_LAMBDA/AWS_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/AWS_SES_LAMBDA/AWS_manager.cpp.s
.PHONY : AWS_SES_LAMBDA/AWS_manager.cpp.s

AWS_SES_LAMBDA/EmailSys.o: AWS_SES_LAMBDA/EmailSys.cpp.o
.PHONY : AWS_SES_LAMBDA/EmailSys.o

# target to build an object file
AWS_SES_LAMBDA/EmailSys.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/AWS_SES_LAMBDA/EmailSys.cpp.o
.PHONY : AWS_SES_LAMBDA/EmailSys.cpp.o

AWS_SES_LAMBDA/EmailSys.i: AWS_SES_LAMBDA/EmailSys.cpp.i
.PHONY : AWS_SES_LAMBDA/EmailSys.i

# target to preprocess a source file
AWS_SES_LAMBDA/EmailSys.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/AWS_SES_LAMBDA/EmailSys.cpp.i
.PHONY : AWS_SES_LAMBDA/EmailSys.cpp.i

AWS_SES_LAMBDA/EmailSys.s: AWS_SES_LAMBDA/EmailSys.cpp.s
.PHONY : AWS_SES_LAMBDA/EmailSys.s

# target to generate assembly for a file
AWS_SES_LAMBDA/EmailSys.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/AWS_SES_LAMBDA/EmailSys.cpp.s
.PHONY : AWS_SES_LAMBDA/EmailSys.cpp.s

Cryptography/SeedCipher.o: Cryptography/SeedCipher.cpp.o
.PHONY : Cryptography/SeedCipher.o

# target to build an object file
Cryptography/SeedCipher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/Cryptography/SeedCipher.cpp.o
.PHONY : Cryptography/SeedCipher.cpp.o

Cryptography/SeedCipher.i: Cryptography/SeedCipher.cpp.i
.PHONY : Cryptography/SeedCipher.i

# target to preprocess a source file
Cryptography/SeedCipher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/Cryptography/SeedCipher.cpp.i
.PHONY : Cryptography/SeedCipher.cpp.i

Cryptography/SeedCipher.s: Cryptography/SeedCipher.cpp.s
.PHONY : Cryptography/SeedCipher.s

# target to generate assembly for a file
Cryptography/SeedCipher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/Cryptography/SeedCipher.cpp.s
.PHONY : Cryptography/SeedCipher.cpp.s

Cryptography/cryptography.o: Cryptography/cryptography.cpp.o
.PHONY : Cryptography/cryptography.o

# target to build an object file
Cryptography/cryptography.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Cryptography/cryptography.cpp.o
.PHONY : Cryptography/cryptography.cpp.o

Cryptography/cryptography.i: Cryptography/cryptography.cpp.i
.PHONY : Cryptography/cryptography.i

# target to preprocess a source file
Cryptography/cryptography.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Cryptography/cryptography.cpp.i
.PHONY : Cryptography/cryptography.cpp.i

Cryptography/cryptography.s: Cryptography/cryptography.cpp.s
.PHONY : Cryptography/cryptography.s

# target to generate assembly for a file
Cryptography/cryptography.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Cryptography/cryptography.cpp.s
.PHONY : Cryptography/cryptography.cpp.s

Database/database_comm.o: Database/database_comm.cpp.o
.PHONY : Database/database_comm.o

# target to build an object file
Database/database_comm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Database/database_comm.cpp.o
.PHONY : Database/database_comm.cpp.o

Database/database_comm.i: Database/database_comm.cpp.i
.PHONY : Database/database_comm.i

# target to preprocess a source file
Database/database_comm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Database/database_comm.cpp.i
.PHONY : Database/database_comm.cpp.i

Database/database_comm.s: Database/database_comm.cpp.s
.PHONY : Database/database_comm.s

# target to generate assembly for a file
Database/database_comm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Database/database_comm.cpp.s
.PHONY : Database/database_comm.cpp.s

Database/database_manager.o: Database/database_manager.cpp.o
.PHONY : Database/database_manager.o

# target to build an object file
Database/database_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Database/database_manager.cpp.o
.PHONY : Database/database_manager.cpp.o

Database/database_manager.i: Database/database_manager.cpp.i
.PHONY : Database/database_manager.i

# target to preprocess a source file
Database/database_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Database/database_manager.cpp.i
.PHONY : Database/database_manager.cpp.i

Database/database_manager.s: Database/database_manager.cpp.s
.PHONY : Database/database_manager.s

# target to generate assembly for a file
Database/database_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Database/database_manager.cpp.s
.PHONY : Database/database_manager.cpp.s

DatabaseV2/DBService.o: DatabaseV2/DBService.cpp.o
.PHONY : DatabaseV2/DBService.o

# target to build an object file
DatabaseV2/DBService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/DBService.cpp.o
.PHONY : DatabaseV2/DBService.cpp.o

DatabaseV2/DBService.i: DatabaseV2/DBService.cpp.i
.PHONY : DatabaseV2/DBService.i

# target to preprocess a source file
DatabaseV2/DBService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/DBService.cpp.i
.PHONY : DatabaseV2/DBService.cpp.i

DatabaseV2/DBService.s: DatabaseV2/DBService.cpp.s
.PHONY : DatabaseV2/DBService.s

# target to generate assembly for a file
DatabaseV2/DBService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/DBService.cpp.s
.PHONY : DatabaseV2/DBService.cpp.s

DatabaseV2/EmailServices/EmailDAO.o: DatabaseV2/EmailServices/EmailDAO.cpp.o
.PHONY : DatabaseV2/EmailServices/EmailDAO.o

# target to build an object file
DatabaseV2/EmailServices/EmailDAO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/EmailServices/EmailDAO.cpp.o
.PHONY : DatabaseV2/EmailServices/EmailDAO.cpp.o

DatabaseV2/EmailServices/EmailDAO.i: DatabaseV2/EmailServices/EmailDAO.cpp.i
.PHONY : DatabaseV2/EmailServices/EmailDAO.i

# target to preprocess a source file
DatabaseV2/EmailServices/EmailDAO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/EmailServices/EmailDAO.cpp.i
.PHONY : DatabaseV2/EmailServices/EmailDAO.cpp.i

DatabaseV2/EmailServices/EmailDAO.s: DatabaseV2/EmailServices/EmailDAO.cpp.s
.PHONY : DatabaseV2/EmailServices/EmailDAO.s

# target to generate assembly for a file
DatabaseV2/EmailServices/EmailDAO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/EmailServices/EmailDAO.cpp.s
.PHONY : DatabaseV2/EmailServices/EmailDAO.cpp.s

DatabaseV2/GenericStuff/Scheduler.o: DatabaseV2/GenericStuff/Scheduler.cpp.o
.PHONY : DatabaseV2/GenericStuff/Scheduler.o

# target to build an object file
DatabaseV2/GenericStuff/Scheduler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/GenericStuff/Scheduler.cpp.o
.PHONY : DatabaseV2/GenericStuff/Scheduler.cpp.o

DatabaseV2/GenericStuff/Scheduler.i: DatabaseV2/GenericStuff/Scheduler.cpp.i
.PHONY : DatabaseV2/GenericStuff/Scheduler.i

# target to preprocess a source file
DatabaseV2/GenericStuff/Scheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/GenericStuff/Scheduler.cpp.i
.PHONY : DatabaseV2/GenericStuff/Scheduler.cpp.i

DatabaseV2/GenericStuff/Scheduler.s: DatabaseV2/GenericStuff/Scheduler.cpp.s
.PHONY : DatabaseV2/GenericStuff/Scheduler.s

# target to generate assembly for a file
DatabaseV2/GenericStuff/Scheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/GenericStuff/Scheduler.cpp.s
.PHONY : DatabaseV2/GenericStuff/Scheduler.cpp.s

DatabaseV2/MobileDeviceServices/DeviceDAO.o: DatabaseV2/MobileDeviceServices/DeviceDAO.cpp.o
.PHONY : DatabaseV2/MobileDeviceServices/DeviceDAO.o

# target to build an object file
DatabaseV2/MobileDeviceServices/DeviceDAO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/MobileDeviceServices/DeviceDAO.cpp.o
.PHONY : DatabaseV2/MobileDeviceServices/DeviceDAO.cpp.o

DatabaseV2/MobileDeviceServices/DeviceDAO.i: DatabaseV2/MobileDeviceServices/DeviceDAO.cpp.i
.PHONY : DatabaseV2/MobileDeviceServices/DeviceDAO.i

# target to preprocess a source file
DatabaseV2/MobileDeviceServices/DeviceDAO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/MobileDeviceServices/DeviceDAO.cpp.i
.PHONY : DatabaseV2/MobileDeviceServices/DeviceDAO.cpp.i

DatabaseV2/MobileDeviceServices/DeviceDAO.s: DatabaseV2/MobileDeviceServices/DeviceDAO.cpp.s
.PHONY : DatabaseV2/MobileDeviceServices/DeviceDAO.s

# target to generate assembly for a file
DatabaseV2/MobileDeviceServices/DeviceDAO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/MobileDeviceServices/DeviceDAO.cpp.s
.PHONY : DatabaseV2/MobileDeviceServices/DeviceDAO.cpp.s

DatabaseV2/UserServices/UserDAO.o: DatabaseV2/UserServices/UserDAO.cpp.o
.PHONY : DatabaseV2/UserServices/UserDAO.o

# target to build an object file
DatabaseV2/UserServices/UserDAO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/UserServices/UserDAO.cpp.o
.PHONY : DatabaseV2/UserServices/UserDAO.cpp.o

DatabaseV2/UserServices/UserDAO.i: DatabaseV2/UserServices/UserDAO.cpp.i
.PHONY : DatabaseV2/UserServices/UserDAO.i

# target to preprocess a source file
DatabaseV2/UserServices/UserDAO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/UserServices/UserDAO.cpp.i
.PHONY : DatabaseV2/UserServices/UserDAO.cpp.i

DatabaseV2/UserServices/UserDAO.s: DatabaseV2/UserServices/UserDAO.cpp.s
.PHONY : DatabaseV2/UserServices/UserDAO.s

# target to generate assembly for a file
DatabaseV2/UserServices/UserDAO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/UserServices/UserDAO.cpp.s
.PHONY : DatabaseV2/UserServices/UserDAO.cpp.s

DatabaseV2/database_comm_v2.o: DatabaseV2/database_comm_v2.cpp.o
.PHONY : DatabaseV2/database_comm_v2.o

# target to build an object file
DatabaseV2/database_comm_v2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/database_comm_v2.cpp.o
.PHONY : DatabaseV2/database_comm_v2.cpp.o

DatabaseV2/database_comm_v2.i: DatabaseV2/database_comm_v2.cpp.i
.PHONY : DatabaseV2/database_comm_v2.i

# target to preprocess a source file
DatabaseV2/database_comm_v2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/database_comm_v2.cpp.i
.PHONY : DatabaseV2/database_comm_v2.cpp.i

DatabaseV2/database_comm_v2.s: DatabaseV2/database_comm_v2.cpp.s
.PHONY : DatabaseV2/database_comm_v2.s

# target to generate assembly for a file
DatabaseV2/database_comm_v2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/DatabaseV2/database_comm_v2.cpp.s
.PHONY : DatabaseV2/database_comm_v2.cpp.s

Implementations/conn_data_storage.o: Implementations/conn_data_storage.cpp.o
.PHONY : Implementations/conn_data_storage.o

# target to build an object file
Implementations/conn_data_storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Implementations/conn_data_storage.cpp.o
.PHONY : Implementations/conn_data_storage.cpp.o

Implementations/conn_data_storage.i: Implementations/conn_data_storage.cpp.i
.PHONY : Implementations/conn_data_storage.i

# target to preprocess a source file
Implementations/conn_data_storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Implementations/conn_data_storage.cpp.i
.PHONY : Implementations/conn_data_storage.cpp.i

Implementations/conn_data_storage.s: Implementations/conn_data_storage.cpp.s
.PHONY : Implementations/conn_data_storage.s

# target to generate assembly for a file
Implementations/conn_data_storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Implementations/conn_data_storage.cpp.s
.PHONY : Implementations/conn_data_storage.cpp.s

Implementations/conn_thread_pool.o: Implementations/conn_thread_pool.cpp.o
.PHONY : Implementations/conn_thread_pool.o

# target to build an object file
Implementations/conn_thread_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Implementations/conn_thread_pool.cpp.o
.PHONY : Implementations/conn_thread_pool.cpp.o

Implementations/conn_thread_pool.i: Implementations/conn_thread_pool.cpp.i
.PHONY : Implementations/conn_thread_pool.i

# target to preprocess a source file
Implementations/conn_thread_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Implementations/conn_thread_pool.cpp.i
.PHONY : Implementations/conn_thread_pool.cpp.i

Implementations/conn_thread_pool.s: Implementations/conn_thread_pool.cpp.s
.PHONY : Implementations/conn_thread_pool.s

# target to generate assembly for a file
Implementations/conn_thread_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Implementations/conn_thread_pool.cpp.s
.PHONY : Implementations/conn_thread_pool.cpp.s

Implementations/connection_data_queue.o: Implementations/connection_data_queue.cpp.o
.PHONY : Implementations/connection_data_queue.o

# target to build an object file
Implementations/connection_data_queue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Implementations/connection_data_queue.cpp.o
.PHONY : Implementations/connection_data_queue.cpp.o

Implementations/connection_data_queue.i: Implementations/connection_data_queue.cpp.i
.PHONY : Implementations/connection_data_queue.i

# target to preprocess a source file
Implementations/connection_data_queue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Implementations/connection_data_queue.cpp.i
.PHONY : Implementations/connection_data_queue.cpp.i

Implementations/connection_data_queue.s: Implementations/connection_data_queue.cpp.s
.PHONY : Implementations/connection_data_queue.s

# target to generate assembly for a file
Implementations/connection_data_queue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Implementations/connection_data_queue.cpp.s
.PHONY : Implementations/connection_data_queue.cpp.s

Implementations/global_thread_pool_tmp.o: Implementations/global_thread_pool_tmp.cpp.o
.PHONY : Implementations/global_thread_pool_tmp.o

# target to build an object file
Implementations/global_thread_pool_tmp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/Implementations/global_thread_pool_tmp.cpp.o
.PHONY : Implementations/global_thread_pool_tmp.cpp.o

Implementations/global_thread_pool_tmp.i: Implementations/global_thread_pool_tmp.cpp.i
.PHONY : Implementations/global_thread_pool_tmp.i

# target to preprocess a source file
Implementations/global_thread_pool_tmp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/Implementations/global_thread_pool_tmp.cpp.i
.PHONY : Implementations/global_thread_pool_tmp.cpp.i

Implementations/global_thread_pool_tmp.s: Implementations/global_thread_pool_tmp.cpp.s
.PHONY : Implementations/global_thread_pool_tmp.s

# target to generate assembly for a file
Implementations/global_thread_pool_tmp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/Implementations/global_thread_pool_tmp.cpp.s
.PHONY : Implementations/global_thread_pool_tmp.cpp.s

Implementations/parse_message_json.o: Implementations/parse_message_json.cpp.o
.PHONY : Implementations/parse_message_json.o

# target to build an object file
Implementations/parse_message_json.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/Implementations/parse_message_json.cpp.o
.PHONY : Implementations/parse_message_json.cpp.o

Implementations/parse_message_json.i: Implementations/parse_message_json.cpp.i
.PHONY : Implementations/parse_message_json.i

# target to preprocess a source file
Implementations/parse_message_json.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/Implementations/parse_message_json.cpp.i
.PHONY : Implementations/parse_message_json.cpp.i

Implementations/parse_message_json.s: Implementations/parse_message_json.cpp.s
.PHONY : Implementations/parse_message_json.s

# target to generate assembly for a file
Implementations/parse_message_json.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/Implementations/parse_message_json.cpp.s
.PHONY : Implementations/parse_message_json.cpp.s

Implementations/server_thread_work.o: Implementations/server_thread_work.cpp.o
.PHONY : Implementations/server_thread_work.o

# target to build an object file
Implementations/server_thread_work.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Implementations/server_thread_work.cpp.o
.PHONY : Implementations/server_thread_work.cpp.o

Implementations/server_thread_work.i: Implementations/server_thread_work.cpp.i
.PHONY : Implementations/server_thread_work.i

# target to preprocess a source file
Implementations/server_thread_work.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Implementations/server_thread_work.cpp.i
.PHONY : Implementations/server_thread_work.cpp.i

Implementations/server_thread_work.s: Implementations/server_thread_work.cpp.s
.PHONY : Implementations/server_thread_work.s

# target to generate assembly for a file
Implementations/server_thread_work.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/Implementations/server_thread_work.cpp.s
.PHONY : Implementations/server_thread_work.cpp.s

Implementations/validate_username.o: Implementations/validate_username.cpp.o
.PHONY : Implementations/validate_username.o

# target to build an object file
Implementations/validate_username.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/Implementations/validate_username.cpp.o
.PHONY : Implementations/validate_username.cpp.o

Implementations/validate_username.i: Implementations/validate_username.cpp.i
.PHONY : Implementations/validate_username.i

# target to preprocess a source file
Implementations/validate_username.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/Implementations/validate_username.cpp.i
.PHONY : Implementations/validate_username.cpp.i

Implementations/validate_username.s: Implementations/validate_username.cpp.s
.PHONY : Implementations/validate_username.s

# target to generate assembly for a file
Implementations/validate_username.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/Implementations/validate_username.cpp.s
.PHONY : Implementations/validate_username.cpp.s

MainEventLoop/main_helpers.o: MainEventLoop/main_helpers.cpp.o
.PHONY : MainEventLoop/main_helpers.o

# target to build an object file
MainEventLoop/main_helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/MainEventLoop/main_helpers.cpp.o
.PHONY : MainEventLoop/main_helpers.cpp.o

MainEventLoop/main_helpers.i: MainEventLoop/main_helpers.cpp.i
.PHONY : MainEventLoop/main_helpers.i

# target to preprocess a source file
MainEventLoop/main_helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/MainEventLoop/main_helpers.cpp.i
.PHONY : MainEventLoop/main_helpers.cpp.i

MainEventLoop/main_helpers.s: MainEventLoop/main_helpers.cpp.s
.PHONY : MainEventLoop/main_helpers.s

# target to generate assembly for a file
MainEventLoop/main_helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/MainEventLoop/main_helpers.cpp.s
.PHONY : MainEventLoop/main_helpers.cpp.s

User/EmailRecovery.o: User/EmailRecovery.cpp.o
.PHONY : User/EmailRecovery.o

# target to build an object file
User/EmailRecovery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/User/EmailRecovery.cpp.o
.PHONY : User/EmailRecovery.cpp.o

User/EmailRecovery.i: User/EmailRecovery.cpp.i
.PHONY : User/EmailRecovery.i

# target to preprocess a source file
User/EmailRecovery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/User/EmailRecovery.cpp.i
.PHONY : User/EmailRecovery.cpp.i

User/EmailRecovery.s: User/EmailRecovery.cpp.s
.PHONY : User/EmailRecovery.s

# target to generate assembly for a file
User/EmailRecovery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/User/EmailRecovery.cpp.s
.PHONY : User/EmailRecovery.cpp.s

User/UserCreation.o: User/UserCreation.cpp.o
.PHONY : User/UserCreation.o

# target to build an object file
User/UserCreation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/User/UserCreation.cpp.o
.PHONY : User/UserCreation.cpp.o

User/UserCreation.i: User/UserCreation.cpp.i
.PHONY : User/UserCreation.i

# target to preprocess a source file
User/UserCreation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/User/UserCreation.cpp.i
.PHONY : User/UserCreation.cpp.i

User/UserCreation.s: User/UserCreation.cpp.s
.PHONY : User/UserCreation.s

# target to generate assembly for a file
User/UserCreation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/User/UserCreation.cpp.s
.PHONY : User/UserCreation.cpp.s

User/UserRecovery.o: User/UserRecovery.cpp.o
.PHONY : User/UserRecovery.o

# target to build an object file
User/UserRecovery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/User/UserRecovery.cpp.o
.PHONY : User/UserRecovery.cpp.o

User/UserRecovery.i: User/UserRecovery.cpp.i
.PHONY : User/UserRecovery.i

# target to preprocess a source file
User/UserRecovery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/User/UserRecovery.cpp.i
.PHONY : User/UserRecovery.cpp.i

User/UserRecovery.s: User/UserRecovery.cpp.s
.PHONY : User/UserRecovery.s

# target to generate assembly for a file
User/UserRecovery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/User/UserRecovery.cpp.s
.PHONY : User/UserRecovery.cpp.s

async_http/mobile_api_handler.o: async_http/mobile_api_handler.cpp.o
.PHONY : async_http/mobile_api_handler.o

# target to build an object file
async_http/mobile_api_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/async_http/mobile_api_handler.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/async_http/mobile_api_handler.cpp.o
.PHONY : async_http/mobile_api_handler.cpp.o

async_http/mobile_api_handler.i: async_http/mobile_api_handler.cpp.i
.PHONY : async_http/mobile_api_handler.i

# target to preprocess a source file
async_http/mobile_api_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/async_http/mobile_api_handler.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/async_http/mobile_api_handler.cpp.i
.PHONY : async_http/mobile_api_handler.cpp.i

async_http/mobile_api_handler.s: async_http/mobile_api_handler.cpp.s
.PHONY : async_http/mobile_api_handler.s

# target to generate assembly for a file
async_http/mobile_api_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_data.dir/build.make CMakeFiles/bastion_data.dir/async_http/mobile_api_handler.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/async_http/mobile_api_handler.cpp.s
.PHONY : async_http/mobile_api_handler.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bastion_auth.dir/build.make CMakeFiles/bastion_auth.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bastion_auth"
	@echo "... bastion_data"
	@echo "... APNS/ios_notifications.o"
	@echo "... APNS/ios_notifications.i"
	@echo "... APNS/ios_notifications.s"
	@echo "... AWS_SES_LAMBDA/AWS_manager.o"
	@echo "... AWS_SES_LAMBDA/AWS_manager.i"
	@echo "... AWS_SES_LAMBDA/AWS_manager.s"
	@echo "... AWS_SES_LAMBDA/EmailSys.o"
	@echo "... AWS_SES_LAMBDA/EmailSys.i"
	@echo "... AWS_SES_LAMBDA/EmailSys.s"
	@echo "... Cryptography/SeedCipher.o"
	@echo "... Cryptography/SeedCipher.i"
	@echo "... Cryptography/SeedCipher.s"
	@echo "... Cryptography/cryptography.o"
	@echo "... Cryptography/cryptography.i"
	@echo "... Cryptography/cryptography.s"
	@echo "... Database/database_comm.o"
	@echo "... Database/database_comm.i"
	@echo "... Database/database_comm.s"
	@echo "... Database/database_manager.o"
	@echo "... Database/database_manager.i"
	@echo "... Database/database_manager.s"
	@echo "... DatabaseV2/DBService.o"
	@echo "... DatabaseV2/DBService.i"
	@echo "... DatabaseV2/DBService.s"
	@echo "... DatabaseV2/EmailServices/EmailDAO.o"
	@echo "... DatabaseV2/EmailServices/EmailDAO.i"
	@echo "... DatabaseV2/EmailServices/EmailDAO.s"
	@echo "... DatabaseV2/GenericStuff/Scheduler.o"
	@echo "... DatabaseV2/GenericStuff/Scheduler.i"
	@echo "... DatabaseV2/GenericStuff/Scheduler.s"
	@echo "... DatabaseV2/MobileDeviceServices/DeviceDAO.o"
	@echo "... DatabaseV2/MobileDeviceServices/DeviceDAO.i"
	@echo "... DatabaseV2/MobileDeviceServices/DeviceDAO.s"
	@echo "... DatabaseV2/UserServices/UserDAO.o"
	@echo "... DatabaseV2/UserServices/UserDAO.i"
	@echo "... DatabaseV2/UserServices/UserDAO.s"
	@echo "... DatabaseV2/database_comm_v2.o"
	@echo "... DatabaseV2/database_comm_v2.i"
	@echo "... DatabaseV2/database_comm_v2.s"
	@echo "... Implementations/conn_data_storage.o"
	@echo "... Implementations/conn_data_storage.i"
	@echo "... Implementations/conn_data_storage.s"
	@echo "... Implementations/conn_thread_pool.o"
	@echo "... Implementations/conn_thread_pool.i"
	@echo "... Implementations/conn_thread_pool.s"
	@echo "... Implementations/connection_data_queue.o"
	@echo "... Implementations/connection_data_queue.i"
	@echo "... Implementations/connection_data_queue.s"
	@echo "... Implementations/global_thread_pool_tmp.o"
	@echo "... Implementations/global_thread_pool_tmp.i"
	@echo "... Implementations/global_thread_pool_tmp.s"
	@echo "... Implementations/parse_message_json.o"
	@echo "... Implementations/parse_message_json.i"
	@echo "... Implementations/parse_message_json.s"
	@echo "... Implementations/server_thread_work.o"
	@echo "... Implementations/server_thread_work.i"
	@echo "... Implementations/server_thread_work.s"
	@echo "... Implementations/validate_username.o"
	@echo "... Implementations/validate_username.i"
	@echo "... Implementations/validate_username.s"
	@echo "... MainEventLoop/main_helpers.o"
	@echo "... MainEventLoop/main_helpers.i"
	@echo "... MainEventLoop/main_helpers.s"
	@echo "... User/EmailRecovery.o"
	@echo "... User/EmailRecovery.i"
	@echo "... User/EmailRecovery.s"
	@echo "... User/UserCreation.o"
	@echo "... User/UserCreation.i"
	@echo "... User/UserCreation.s"
	@echo "... User/UserRecovery.o"
	@echo "... User/UserRecovery.i"
	@echo "... User/UserRecovery.s"
	@echo "... async_http/mobile_api_handler.o"
	@echo "... async_http/mobile_api_handler.i"
	@echo "... async_http/mobile_api_handler.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

